FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14 AS builder
WORKDIR /go/src/github.com/openshift/origin
COPY . .
RUN make; \
    mkdir -p /tmp/build; \
    cp /go/src/github.com/openshift/origin/openshift-tests /tmp/build/openshift-tests

FROM registry.ci.openshift.org/ocp/4.14:tools
COPY --from=builder /tmp/build/openshift-tests /usr/bin/
RUN source /etc/os-release; PACKAGES="git gzip util-linux" && \
    if [ $HOSTTYPE = x86_64 ] || [ $HOSTTYPE = ppc64le ]; then PACKAGES="$PACKAGES python3-cinderclient"; fi && \
    # rt-tests in RHEL8/CS8, realtime-tests in RHEL9/CS9
    if [ $HOSTTYPE = x86_64 ] && [ $VERSION_ID -lt 9 ]; then PACKAGES="$PACKAGES rt-tests"; fi && \
    if [ $HOSTTYPE = x86_64 ] && [ $VERSION_ID -ge 9 ]; then PACKAGES="$PACKAGES realtime-tests"; fi && \
    # centos-release-openstack-* enables the openstack repo, required to install python3-cinderclient in CentOS Stream
    if [ $ID == "centos" ]; then dnf install -y centos-release-openstack-zed; fi && \
    yum install --setopt=tsflags=nodocs -y $PACKAGES && \
    yum update -y python3-six && \
    yum clean all && rm -rf /var/cache/yum/* && \
    git config --system user.name test && \
    git config --system user.email test@test.com && \
    chmod g+w /etc/passwd
LABEL io.k8s.display-name="OpenShift End-to-End Tests" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,tests,e2e"
